import { escapeLuaString, expandStatsFromCategory, clamp } from './utils'
import { POSITION_TO_CODE, CATEGORY_FIELDS } from './constants'

export function generateLuaScript(player) {
  const safeFirstName = escapeLuaString(player.firstName)
  const safeLastName = escapeLuaString(player.lastName)
  const safeJerseyName = escapeLuaString(player.jerseyName)
  const statFields = expandStatsFromCategory(player.ratings, player.position)
  const rows = [
    `overallrating = "${player.overall}"`,
    'potential = "99"',
    `preferredposition1 = "${POSITION_TO_CODE[player.position] ?? POSITION_TO_CODE.CM}"`,
    'preferredposition2 = "-1"',
    'preferredposition3 = "-1"',
    'preferredposition4 = "-1"',
    `nationality = "${player.nationality}"`,
    'birthdate = birthdate_days',
    `height = "${player.height}"`,
    `weight = "${player.weight}"`,
    'gender = "0"',
    'usercaneditname = "1"',
  ]

  Object.entries(statFields).forEach(([field, value]) => {
    rows.push(`${field} = "${value}"`)
  })

  const statBlock = rows.map((line) => `    ${line},`).join('\n')

  return `-- Generated by FC26 Career Builder v2
require 'imports/career_mode/helpers'
require 'imports/other/helpers'

if not IsInCM() then
    MessageBox("Error", "Must be in Career Mode!")
    return
end

local target_age = ${player.age}
local current_date = GetCurrentDate()
local birthdate_date = DATE:new()
birthdate_date.day = current_date.day
birthdate_date.month = current_date.month
birthdate_date.year = current_date.year - target_age
local birthdate_days = birthdate_date:ToGregorianDays()

math.randomseed(os.time())
local requested_playerid = 50000 + math.random(0, 49999)
local playerid = requested_playerid

if PlayerExists(playerid) then
    local found_free_id = false
    for i = 1, 5000 do
        local candidate = requested_playerid + i
        if not PlayerExists(candidate) then
            playerid = candidate
            found_free_id = true
            break
        end
    end

    if not found_free_id then
        Log("[PLAYER_BUILDER] Could not find free Player ID after: " .. requested_playerid)
        MessageBox("Error", "No free Player ID found in next 5000 values.")
        return
    end

    Log("[PLAYER_BUILDER] Requested ID " .. requested_playerid .. " exists. Using " .. playerid)
end

local player_data = {
${statBlock}
}

local created_id = CreatePlayer(playerid, player_data)
if created_id == 0 then
    Log("[PLAYER_BUILDER] CreatePlayer failed for ID: " .. playerid)
    MessageBox("Error", "CreatePlayer failed. Check Lua log.")
    return
end

if not PlayerExists(created_id) then
    Log("[PLAYER_BUILDER] Player missing after create. ID: " .. created_id)
    MessageBox("Error", "Player creation did not persist.")
    return
end

local edited_names_rows = GetDBTableRows("editedplayernames")
local existing_name_row = nil
for i = 1, #edited_names_rows do
    local row = edited_names_rows[i]
    if tonumber(row.playerid) == created_id then
        existing_name_row = row
        break
    end
end

if existing_name_row then
    EditDBTableField("editedplayernames", existing_name_row, "firstname", "${safeFirstName}")
    EditDBTableField("editedplayernames", existing_name_row, "surname", "${safeLastName}")
    EditDBTableField("editedplayernames", existing_name_row, "playerjerseyname", "${safeJerseyName}")
    Log("[PLAYER_BUILDER] Name row updated for ID: " .. created_id)
else
    local name_row = InsertDBTableRow("editedplayernames", {
        playerid = string.format("%d", created_id),
        firstname = "${safeFirstName}",
        surname = "${safeLastName}",
        commonname = "",
        playerjerseyname = "${safeJerseyName}"
    })

    if not name_row then
        Log("[PLAYER_BUILDER] Could not insert editedplayernames row for ID: " .. created_id)
    else
        Log("[PLAYER_BUILDER] Name row inserted for ID: " .. created_id)
    end
end

local players_rows = GetDBTableRows("players")
local player_row = nil
for i = 1, #players_rows do
    local row = players_rows[i]
    if tonumber(row.playerid) == created_id then
        player_row = row
        break
    end
end

if player_row then
    if player_row.usercaneditname ~= nil then
        EditDBTableField("players", player_row, "usercaneditname", "1")
    end
    if player_row.birthdate ~= nil then
      EditDBTableField("players", player_row, "birthdate", tostring(birthdate_days))
    end
    if player_row.firstnameid ~= nil then
        EditDBTableField("players", player_row, "firstnameid", "0")
    end
    if player_row.surnameid ~= nil then
        EditDBTableField("players", player_row, "surnameid", "0")
    end
    if player_row.commonnameid ~= nil then
        EditDBTableField("players", player_row, "commonnameid", "0")
    end
    if player_row.knownas ~= nil then
        EditDBTableField("players", player_row, "knownas", "0")
    end
end

if ReloadPlayersManager then
    ReloadPlayersManager()
end

local verify_rows = GetDBTableRows("players")
for i = 1, #verify_rows do
  local row = verify_rows[i]
  if tonumber(row.playerid) == created_id and row.birthdate ~= nil then
    local bd = DATE:new()
    bd:FromGregorianDays(tonumber(row.birthdate))
    local real_age = CalculatePlayerAge(GetCurrentDate(), bd)
    Log("[PLAYER_BUILDER] Verified age: " .. real_age .. " (target: " .. target_age .. ")")
    break
  end
end

MessageBox("Success", "Created ${safeFirstName} ${safeLastName} (ID: " .. created_id .. ") in Free Agents.")
Log("[PLAYER_BUILDER] Created player in Free Agents. Final ID: " .. created_id)
`
}

export function generateMultiLuaScript(players, teamName) {
  if (!players.length) {
    return '-- Generate squad preview first, then your batch Lua script will appear here.'
  }

  const safeTeamName = escapeLuaString(teamName || 'Custom Squad')

  const priorityOrder = { 'XI': 0, 'Subs': 1, 'Reserves': 2 }
  const sortedPlayers = [...players].sort((a, b) => {
    const aPriority = priorityOrder[a.priority] ?? 2
    const bPriority = priorityOrder[b.priority] ?? 2
    return aPriority - bPriority
  })

  const playerEntries = sortedPlayers
    .map((player) => {
      const statFields = expandStatsFromCategory(player.ratings, player.position)
      const statsLua = Object.entries(statFields)
        .map(([field, value]) => `${field} = ${Number(value)}`)
        .join(', ')

      return `    {
        first = "${escapeLuaString(player.firstName)}",
        last = "${escapeLuaString(player.firstName)}",
        jersey = "${escapeLuaString(player.jerseyName)}",
        position = ${POSITION_TO_CODE[player.position] ?? POSITION_TO_CODE.CM},
        nationality = ${Number(player.nationality)},
        age = ${Number(player.age)},
        height = ${Number(player.height)},
        weight = ${Number(player.weight)},
        overall = ${Number(player.overall)},
        stats = { ${statsLua} }
    }`
    })
    .join(',\n')

  return `-- Generated by FC26 Squad Builder
require 'imports/career_mode/helpers'
require 'imports/other/helpers'

if not IsInCM() then
    MessageBox("Error", "Must be in Career Mode!")
    return
end

math.randomseed(os.time())
local created_count = 0
local transferred_count = 0
local transfer_failed_count = 0
local released_existing_count = 0
local release_existing_failed_count = 0
local post_cleanup_removed_count = 0
local post_cleanup_failed_count = 0

local squad_name = "${safeTeamName}"
local user_teamid = GetUserTeamID()
local free_agents_teamid = 111592

if user_teamid == 0 then
  MessageBox("Error", "Could not detect your user team.")
  return
end

local players = {
${playerEntries}
}
local created_player_ids = {}

local function try_transfer(playerid, from_teamid, to_teamid, wage, contract_months)
  local ok, err = pcall(function()
    if TransferPlayer then
      TransferPlayer(playerid, to_teamid, 0, wage, contract_months, from_teamid, 0)
      return
    end

    if cTransferPlayer then
      cTransferPlayer(playerid, from_teamid, to_teamid, 0, 0, wage, contract_months)
      return
    end

    error("No transfer API available")
  end)

  return ok, err
end

local existing_player_ids = GetUserSeniorTeamPlayerIDs()
for existing_playerid, _ in pairs(existing_player_ids) do
  local ok, err = try_transfer(existing_playerid, user_teamid, free_agents_teamid, 0, 12)
  if ok then
    released_existing_count = released_existing_count + 1
  else
    release_existing_failed_count = release_existing_failed_count + 1
    Log("[SQUAD_BUILDER] Could not release existing player " .. tostring(existing_playerid) .. ": " .. tostring(err))
  end
end

local function get_free_player_id()
    local requested_playerid = 50000 + math.random(0, 49999)
    local playerid = requested_playerid

    if not PlayerExists(playerid) then return playerid end

    for i = 1, 5000 do
        local candidate = requested_playerid + i
        if not PlayerExists(candidate) then
            return candidate
        end
    end

    return 0
end

local function upsert_player_name(created_id, p)
    local edited_names_rows = GetDBTableRows("editedplayernames")
    local existing_name_row = nil
    for i = 1, #edited_names_rows do
        local row = edited_names_rows[i]
        if tonumber(row.playerid) == created_id then
            existing_name_row = row
            break
        end
    end

    if existing_name_row then
        EditDBTableField("editedplayernames", existing_name_row, "firstname", p.first)
        EditDBTableField("editedplayernames", existing_name_row, "surname", p.last)
        EditDBTableField("editedplayernames", existing_name_row, "playerjerseyname", p.jersey)
    else
        InsertDBTableRow("editedplayernames", {
            playerid = string.format("%d", created_id),
            firstname = p.first,
            surname = p.last,
            commonname = "",
            playerjerseyname = p.jersey
        })
    end
end

for i = 1, #players do
    local p = players[i]
    local playerid = get_free_player_id()
    if playerid == 0 then
        Log("[SQUAD_BUILDER] Skipped one player, no free ID found")
        goto continue
    end

    local current_date = GetCurrentDate()
    local birthdate_date = DATE:new()
    birthdate_date.day = current_date.day
    birthdate_date.month = current_date.month
    birthdate_date.year = current_date.year - p.age
    local birthdate_days = birthdate_date:ToGregorianDays()

    local player_data = {
        overallrating = tostring(p.overall),
        potential = "99",
        preferredposition1 = tostring(p.position),
        preferredposition2 = "-1",
        preferredposition3 = "-1",
        preferredposition4 = "-1",
        nationality = tostring(p.nationality),
        birthdate = birthdate_days,
        height = tostring(p.height),
        weight = tostring(p.weight),
        gender = "0",
        usercaneditname = "1",
    }

    for key, val in pairs(p.stats) do
        player_data[key] = tostring(val)
    end

    local created_id = CreatePlayer(playerid, player_data)
    if created_id ~= 0 and PlayerExists(created_id) then
        upsert_player_name(created_id, p)
        created_count = created_count + 1

        local transfer_ok, transfer_err = try_transfer(created_id, free_agents_teamid, user_teamid, 500, 60)
        if transfer_ok then
            transferred_count = transferred_count + 1
          created_player_ids[created_id] = true
        else
            transfer_failed_count = transfer_failed_count + 1
            Log("[SQUAD_BUILDER] Transfer failed for ID " .. tostring(created_id) .. ": " .. tostring(transfer_err))
        end
    else
        Log("[SQUAD_BUILDER] Failed to create: " .. p.first .. " " .. p.last)
    end

    ::continue::
end

  local function cleanup_non_generated_players()
    local ids_after_build = GetUserSeniorTeamPlayerIDs()
    for pid, _ in pairs(ids_after_build) do
      if not created_player_ids[pid] then
        local ok, err = try_transfer(pid, user_teamid, free_agents_teamid, 0, 12)
        if ok then
          post_cleanup_removed_count = post_cleanup_removed_count + 1
        else
          post_cleanup_failed_count = post_cleanup_failed_count + 1
          Log("[SQUAD_BUILDER] Post-cleanup failed for player " .. tostring(pid) .. ": " .. tostring(err))
        end
      end
    end
  end

  for pass = 1, 3 do
    cleanup_non_generated_players()
  end

if ReloadPlayersManager then
    ReloadPlayersManager()
end

  MessageBox("Success", "Released existing: " .. released_existing_count .. " (failed: " .. release_existing_failed_count .. ") | Created: " .. created_count .. " | Added to your club: " .. transferred_count .. " (failed: " .. transfer_failed_count .. ") | Post-cleanup removed: " .. post_cleanup_removed_count .. " (failed: " .. post_cleanup_failed_count .. ")")
  Log("[SQUAD_BUILDER] Completed. Released existing: " .. released_existing_count .. ", release failed: " .. release_existing_failed_count .. ", created: " .. created_count .. ", transferred: " .. transferred_count .. ", transfer failed: " .. transfer_failed_count .. ", post-cleanup removed: " .. post_cleanup_removed_count .. ", post-cleanup failed: " .. post_cleanup_failed_count)
`
}

export function generateReleaseAllLuaScript() {
  return `-- Generated by FC26 Team Wipe Tool
require 'imports/career_mode/helpers'
require 'imports/other/helpers'

if not IsInCM() then
  MessageBox("Error", "Must be in Career Mode!")
  return
end

local user_teamid = GetUserTeamID()
local free_agents_teamid = 111592
local removed_count = 0
local failed_count = 0

if user_teamid == 0 then
  MessageBox("Error", "Could not detect your user team.")
  return
end

local function try_release_player(playerid)
  local ok, err = pcall(function()
    if TransferPlayer then
      TransferPlayer(playerid, free_agents_teamid, 0, 0, 12, user_teamid, 0)
      return
    end

    if cTransferPlayer then
      cTransferPlayer(playerid, user_teamid, free_agents_teamid, 0, 0, 0, 12)
      return
    end

    error("No transfer API available")
  end)

  return ok, err
end

local function wipe_pass()
  local player_ids = GetUserSeniorTeamPlayerIDs()
  for playerid, _ in pairs(player_ids) do
    local ok, err = try_release_player(playerid)
    if ok then
      removed_count = removed_count + 1
    else
      failed_count = failed_count + 1
      Log("[TEAM_WIPE] Failed player " .. tostring(playerid) .. ": " .. tostring(err))
    end
  end
end

for i = 1, 5 do
  wipe_pass()
end

if ReloadPlayersManager then
  ReloadPlayersManager()
end

MessageBox("Done", "EVERYTHING WIPE OUT attempted. Removed: " .. removed_count .. " | Failed: " .. failed_count)
Log("[TEAM_WIPE] Completed for team " .. user_teamid .. ". Removed: " .. removed_count .. ", failed: " .. failed_count)
`
}

export function generateHappinessLuaScript(config) {
  const runDaily = config.runDaily ? 'true' : 'false'
  const runPrematch = config.runPrematch ? 'true' : 'false'
  const runOnLoad = config.runOnLoad ? 'true' : 'false'
  const applyNow = config.applyNow ? 'true' : 'false'

  return `-- Generated by FC26 Team Happiness Tool
require 'imports/career_mode/enums'
require 'imports/career_mode/helpers'

local form_value = ${Number(config.form)}
local sharpness_value = ${Number(config.sharpness)}
local morale_value = ${Number(config.morale)}

local run_daily = ${runDaily}
local run_prematch = ${runPrematch}
local run_on_load = ${runOnLoad}

local function ApplyHappinessBoost()
  UserTeamSetPlayersFormSharpnessMorale(
    form_value,
    sharpness_value,
    morale_value
  )
end

function TeamHappiness__OnEvent(events_manager, event_id, event)
  if (
    (run_daily and event_id == ENUM_CM_EVENT_MSG_DAY_PASSED) or
    (run_prematch and event_id == ENUM_CM_EVENT_MSG_ABOUT_TO_ENTER_PREMATCH) or
    (run_on_load and event_id == ENUM_CM_EVENT_MSG_POST_LOAD_PREPARE)
  ) then
    ApplyHappinessBoost()
  end
end

AddEventHandler("post__CareerModeEvent", TeamHappiness__OnEvent)

if (${applyNow} and IsInCM()) then
  ApplyHappinessBoost()
  MessageBox("Done", "Team happiness boost applied: Form ${Number(config.form)}, Sharpness ${Number(config.sharpness)}, Morale ${Number(config.morale)}")
end
`
}

export function generateContractExtensionLuaScript(config) {
  const months = Number(config.months)
  const years = Math.floor(months / 12)
  const remainingMonths = months % 12

  return `-- Generated by FC26 Contract Extension Tool
require 'imports/other/helpers'

local new_contract_length = ${months} -- ${years} years${remainingMonths > 0 ? ` ${remainingMonths} months` : ''}

assert(IsInCM(), "Script must be executed in career mode")

function update_contractvaliduntil(contracts)
    local contracts_to_update = 0
    local updated_contracts = 0

    for playerid, contractvaliduntil in pairs(contracts) do
        contracts_to_update = contracts_to_update + 1
    end

    local players_table = LE.db:GetTable("players")
    local current_record = players_table:GetFirstRecord()

    local playerid = 0
    local contractvaliduntil = nil
    while current_record > 0 do
        if updated_contracts >= contracts_to_update then
            break
        end

        playerid = players_table:GetRecordFieldValue(current_record, "playerid")
        contractvaliduntil = contracts[playerid]
        if contractvaliduntil ~= nil then
            players_table:SetRecordFieldValue(current_record, "contractvaliduntil", contractvaliduntil)
            updated_contracts = updated_contracts + 1
        end
    
        current_record = players_table:GetNextValidRecord()
    end

    local failed_to_update = contracts_to_update - updated_contracts
    
    if failed_to_update > 0 then
        Log(string.format("Failed to update %d contracts", failed_to_update))
    end
    
    Log(string.format("Updated Contracts: %d", updated_contracts))
end

function update_contracts()
    local result = {}

    local currentdate = GetCurrentDate()
    local int_current_date = currentdate:ToInt()

    local career_playercontract_table = LE.db:GetTable("career_playercontract")
    local current_record = career_playercontract_table:GetFirstRecord()

    local playerid = 0
    local contract_status = 0
    local is_loaned_in = false
    local contract_date = 0
    local last_status_change_date = 0
    local contractvaliduntil = 0
    while current_record > 0 do
        contract_status = career_playercontract_table:GetRecordFieldValue(current_record, "contract_status")
        is_loaned_in = (contract_status == 1) or (contract_status == 3) or (contract_status == 5)

        if not is_loaned_in then
            contract_date = career_playercontract_table:GetRecordFieldValue(current_record, "contract_date")
            last_status_change_date = career_playercontract_table:GetRecordFieldValue(current_record, "last_status_change_date")

            if contract_date < int_current_date then
                career_playercontract_table:SetRecordFieldValue(current_record, "contract_date", int_current_date)
            end

            if last_status_change_date < int_current_date then
                career_playercontract_table:SetRecordFieldValue(current_record, "last_status_change_date", int_current_date)
            end

            career_playercontract_table:SetRecordFieldValue(current_record, "duration_months", new_contract_length)

            contractvaliduntil = currentdate.year + math.floor(new_contract_length / 12)

            playerid = career_playercontract_table:GetRecordFieldValue(current_record, "playerid")
            result[playerid] = contractvaliduntil
        end

        current_record = career_playercontract_table:GetNextValidRecord()
    end

    return result
end

update_contractvaliduntil(update_contracts())
Log("[CONTRACT_EXTENSION] Extended all player contracts by ${months} months (${years}y ${remainingMonths}m)")
MessageBox("Done", "All player contracts extended by ${months} months")
`
}

export function generatePlayerLockLuaScript() {
  return `-- Lock All Players to Club (Prevent Transfers)
require 'imports/career_mode/helpers'
require 'imports/other/helpers'

if not IsInCM() then
    MessageBox("Error", "Must be in Career Mode!")
    return
end

local user_team_id = GetUserTeamID()

function update_contracts_lock()
    local result = {}
    local lock_duration_months = 240 -- 20 years to effectively lock players in club
    
    local currentdate = GetCurrentDate()
    local int_current_date = currentdate:ToInt()

    local career_playercontract_table = LE.db:GetTable("career_playercontract")
    local current_record = career_playercontract_table:GetFirstRecord()

    local playerid = 0
    local teamid = 0
    local contract_status = 0
    local is_loaned_in = false
    local contractvaliduntil = 0
    local locked_count = 0
    
    while current_record > 0 do
        teamid = career_playercontract_table:GetRecordFieldValue(current_record, "teamid")
        
        -- Only process players on the user's team
        if teamid == user_team_id then
            playerid = career_playercontract_table:GetRecordFieldValue(current_record, "playerid")
            contract_status = career_playercontract_table:GetRecordFieldValue(current_record, "contract_status")
            is_loaned_in = (contract_status == 1) or (contract_status == 3) or (contract_status == 5)

            -- Only lock players who are not loaned in
            if not is_loaned_in then
                career_playercontract_table:SetRecordFieldValue(current_record, "contract_date", int_current_date)
                career_playercontract_table:SetRecordFieldValue(current_record, "duration_months", lock_duration_months)

                contractvaliduntil = currentdate.year + math.floor(lock_duration_months / 12)

                result[playerid] = contractvaliduntil
                locked_count = locked_count + 1
            end
        end

        current_record = career_playercontract_table:GetNextValidRecord()
    end

    return result, locked_count
end

local locked_players, count = update_contracts_lock()
update_contractvaliduntil(locked_players)

Log("[PLAYER_LOCK] Locked \${count} players to club with 20-year contracts")
MessageBox("Done", "\${count} players locked to club and cannot be transferred")
`
}
