import { useMemo, useState } from 'react'
import './App.css'

const POSITION_WEIGHTS = {
  ST: { shooting: 0.35, pace: 0.2, dribbling: 0.2, physical: 0.15, passing: 0.07, defending: 0.03 },
  CF: { shooting: 0.3, dribbling: 0.24, passing: 0.2, pace: 0.15, physical: 0.08, defending: 0.03 },
  CAM: { passing: 0.34, dribbling: 0.25, pace: 0.12, shooting: 0.16, physical: 0.08, defending: 0.05 },
  CM: { passing: 0.3, dribbling: 0.16, defending: 0.2, physical: 0.14, pace: 0.1, shooting: 0.1 },
  CDM: { defending: 0.34, physical: 0.24, passing: 0.2, pace: 0.1, dribbling: 0.07, shooting: 0.05 },
  CB: { defending: 0.4, physical: 0.28, pace: 0.15, passing: 0.1, dribbling: 0.03, shooting: 0.04 },
  LB: { pace: 0.24, defending: 0.24, passing: 0.18, physical: 0.15, dribbling: 0.13, shooting: 0.06 },
  RB: { pace: 0.24, defending: 0.24, passing: 0.18, physical: 0.15, dribbling: 0.13, shooting: 0.06 },
  LM: { pace: 0.24, dribbling: 0.24, passing: 0.22, shooting: 0.16, physical: 0.08, defending: 0.06 },
  RM: { pace: 0.24, dribbling: 0.24, passing: 0.22, shooting: 0.16, physical: 0.08, defending: 0.06 },
  LW: { pace: 0.24, dribbling: 0.3, shooting: 0.21, passing: 0.14, physical: 0.07, defending: 0.04 },
  RW: { pace: 0.24, dribbling: 0.3, shooting: 0.21, passing: 0.14, physical: 0.07, defending: 0.04 },
}

const POSITION_TO_CODE = {
  GK: 0,
  RB: 3,
  CB: 5,
  LB: 7,
  CDM: 10,
  RM: 12,
  CM: 14,
  LM: 16,
  CAM: 18,
  RW: 23,
  CF: 21,
  ST: 25,
  LW: 27,
}

const STARTING_TEMPLATES = {
  rookie: { min: 52, max: 66, label: 'Rookie Road (Lower Division Start)' },
  semiPro: { min: 62, max: 74, label: 'Semi-Pro Climb' },
  elite: { min: 74, max: 86, label: 'Elite Start' },
}

const DIVISION_OPTIONS = [
  'EFL League Two',
  'EFL League One',
  'EFL Championship',
  'Premier League',
  'Bundesliga 2',
  'Bundesliga',
  'Ligue 2',
  'Ligue 1',
]

const CATEGORY_FIELDS = {
  pace: ['acceleration', 'sprintspeed'],
  shooting: ['finishing', 'shotpower', 'positioning', 'volleys', 'longshots'],
  passing: ['shortpassing', 'longpassing', 'crossing', 'vision'],
  dribbling: ['dribbling', 'ballcontrol', 'agility', 'balance'],
  defending: ['defensiveawareness', 'standingtackle', 'slidingtackle', 'interceptions'],
  physical: ['strength', 'stamina', 'jumping', 'aggression'],
}

const clamp = (value, min, max) => Math.max(min, Math.min(max, value))
const escapeLuaString = (value) => String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')

function categoryAverage(ratings) {
  return Math.round(
    (ratings.pace + ratings.shooting + ratings.passing + ratings.dribbling + ratings.defending + ratings.physical) / 6,
  )
}

function computeSuggestedOverall(position, ratings, template) {
  const weights = POSITION_WEIGHTS[position] || POSITION_WEIGHTS.CM
  const weighted =
    ratings.pace * weights.pace +
    ratings.shooting * weights.shooting +
    ratings.passing * weights.passing +
    ratings.dribbling * weights.dribbling +
    ratings.defending * weights.defending +
    ratings.physical * weights.physical

  const squadCap = STARTING_TEMPLATES[template] || STARTING_TEMPLATES.rookie
  return clamp(Math.round(weighted), squadCap.min, squadCap.max)
}

function expandStatsFromCategory(ratings) {
  const stats = {}

  Object.entries(CATEGORY_FIELDS).forEach(([group, fields]) => {
    fields.forEach((fieldName) => {
      stats[fieldName] = ratings[group]
    })
  })

  return stats
}

function generateLuaScript(player) {
  const safeFirstName = escapeLuaString(player.firstName)
  const safeLastName = escapeLuaString(player.lastName)
  const safeJerseyName = escapeLuaString(player.jerseyName)
  const safeDivisionName = escapeLuaString(player.targetDivision)
  const statFields = expandStatsFromCategory(player.ratings)
  const rows = [
    `overallrating = "${player.overall}"`,
    `potential = "${player.potential}"`,
    `preferredposition1 = "${POSITION_TO_CODE[player.position] ?? POSITION_TO_CODE.CM}"`,
    `preferredposition2 = "-1"`,
    `preferredposition3 = "-1"`,
    `preferredposition4 = "-1"`,
    `nationality = "${player.nationality}"`,
    `height = "${player.height}"`,
    `weight = "${player.weight}"`,
    `gender = "0"`,
    `usercaneditname = "1"`,
  ]

  Object.entries(statFields).forEach(([field, value]) => {
    rows.push(`${field} = "${value}"`)
  })

  const statBlock = rows.map((line) => `    ${line},`).join('\n')

  return `-- Generated by FC26 Career Builder (React MVP)
require 'imports/career_mode/helpers'

if not IsInCM() then
    MessageBox("Error", "Must be in Career Mode!")
    return
end

local playerid = ${player.playerId}
local requested_playerid = playerid

if PlayerExists(playerid) then
  local found_free_id = false
  for i = 1, 5000 do
    local candidate = requested_playerid + i
    if not PlayerExists(candidate) then
      playerid = candidate
      found_free_id = true
      break
    end
  end

  if not found_free_id then
    Log("[PLAYER_BUILDER] Could not find free Player ID after: " .. requested_playerid)
    MessageBox("Error", "Player ID already exists and no free ID was found in next 5000 values.")
    return
  end

  Log("[PLAYER_BUILDER] Requested Player ID " .. requested_playerid .. " already existed. Using " .. playerid)
end

local player_data = {
${statBlock}
}

local created_id = CreatePlayer(playerid, player_data)

if created_id == 0 then
  Log("[PLAYER_BUILDER] CreatePlayer failed for ID: " .. playerid .. " (requested: " .. requested_playerid .. ")")
  MessageBox("Error", "CreatePlayer failed. Check Lua log and try a different Player ID.")
  return
end

if not PlayerExists(created_id) then
  Log("[PLAYER_BUILDER] Player does not exist after CreatePlayer. ID: " .. created_id)
  MessageBox("Error", "Player creation did not persist in database.")
  return
end

-- Upsert name row in editedplayernames to ensure visible custom name.
local edited_names_rows = GetDBTableRows("editedplayernames")
local existing_name_row = nil
for i = 1, #edited_names_rows do
  local row = edited_names_rows[i]
  if tonumber(row.playerid) == created_id then
    existing_name_row = row
    break
  end
end

if existing_name_row then
  EditDBTableField("editedplayernames", existing_name_row, "firstname", "${safeFirstName}")
  EditDBTableField("editedplayernames", existing_name_row, "surname", "${safeLastName}")
  EditDBTableField("editedplayernames", existing_name_row, "playerjerseyname", "${safeJerseyName}")
  Log("[PLAYER_BUILDER] Name row updated for ID: " .. created_id)
else
  local name_row = InsertDBTableRow("editedplayernames", {
    playerid = string.format("%d", created_id),
    firstname = "${safeFirstName}",
    surname = "${safeLastName}",
    commonname = "",
    playerjerseyname = "${safeJerseyName}"
  })

  if not name_row then
    Log("[PLAYER_BUILDER] Could not insert editedplayernames row for ID: " .. created_id)
  else
    Log("[PLAYER_BUILDER] Name row inserted for ID: " .. created_id)
  end
end

-- Patch players row directly as fallback for saves that ignore editedplayernames until reload.
local players_rows = GetDBTableRows("players")
local player_row = nil
for i = 1, #players_rows do
  local row = players_rows[i]
  if tonumber(row.playerid) == created_id then
    player_row = row
    break
  end
end

if player_row then
  if player_row.usercaneditname ~= nil then
    EditDBTableField("players", player_row, "usercaneditname", "1")
  end
  if player_row.firstnameid ~= nil then
    EditDBTableField("players", player_row, "firstnameid", "0")
  end
  if player_row.surnameid ~= nil then
    EditDBTableField("players", player_row, "surnameid", "0")
  end
  if player_row.commonnameid ~= nil then
    EditDBTableField("players", player_row, "commonnameid", "0")
  end
  if player_row.knownas ~= nil then
    EditDBTableField("players", player_row, "knownas", "0")
  end
  Log("[PLAYER_BUILDER] Players row patched for naming fallback. ID: " .. created_id)
else
  Log("[PLAYER_BUILDER] Could not find players row for ID: " .. created_id)
end

if ReloadPlayersManager then
  ReloadPlayersManager()
end

local before_teamid = GetTeamIdFromPlayerId(created_id)
Log("[PLAYER_BUILDER] Created player ID: " .. created_id .. " | Requested ID: " .. requested_playerid .. " | Initial teamid: " .. before_teamid)

if ${player.addToUserTeam ? 'true' : 'false'} then
  local user_teamid = GetUserTeamID()
  TransferPlayer(created_id, user_teamid, 1, ${player.wage}, ${player.contractMonths}, before_teamid > 0 and before_teamid or 0)

  local after_teamid = GetTeamIdFromPlayerId(created_id)
  Log("[PLAYER_BUILDER] Transfer attempt -> user teamid: " .. user_teamid .. " | current teamid: " .. after_teamid)

  if after_teamid == user_teamid then
    MessageBox("Success", "Created ${safeFirstName} ${safeLastName} in your team (ID: " .. created_id .. ")")
  else
    MessageBox("Partial Success", "Player created (ID: " .. created_id .. "), but transfer did not complete. Check Free Agents and use manual transfer.")
  end
else
  MessageBox("Success", "Created ${safeFirstName} ${safeLastName} (ID: " .. created_id .. "). Check Free Agents.")
end

Log("[PLAYER_BUILDER] Division plan: ${safeDivisionName}")
`
}

function App() {
  const [form, setForm] = useState({
    firstName: 'Mahmut',
    lastName: 'Career',
    jerseyName: 'MAHMUT',
    age: 22,
    position: 'CB',
    template: 'rookie',
    targetDivision: 'EFL League Two',
    potential: 99,
    addToUserTeam: true,
    nationality: 14,
    playerId: 50010,
    contractMonths: 60,
    wage: 1500,
    height: 184,
    weight: 78,
    ratings: {
      pace: 58,
      shooting: 43,
      passing: 57,
      dribbling: 53,
      defending: 65,
      physical: 66,
    },
  })

  const suggestedOverall = useMemo(
    () => computeSuggestedOverall(form.position, form.ratings, form.template),
    [form.position, form.ratings, form.template],
  )

  const averageCategory = useMemo(() => categoryAverage(form.ratings), [form.ratings])
  const luaScript = useMemo(
    () =>
      generateLuaScript({
        ...form,
        overall: suggestedOverall,
      }),
    [form, suggestedOverall],
  )

  function updateField(field, value) {
    setForm((prev) => ({ ...prev, [field]: value }))
  }

  function updateRating(field, value) {
    const numberValue = Number(value)
    setForm((prev) => ({
      ...prev,
      ratings: {
        ...prev.ratings,
        [field]: numberValue,
      },
    }))
  }

  async function copyLuaScript() {
    try {
      await navigator.clipboard.writeText(luaScript)
      window.alert('Lua script copied to clipboard!')
    } catch {
      window.alert('Could not copy automatically. Select and copy manually.')
    }
  }

  return (
    <main className="layout">
      <header className="hero">
        <p className="eyebrow">FC26 Career Mode Tool</p>
        <h1>Player Builder + Lua Generator</h1>
        <p>
          First milestone: create one player profile, answer useful rating questions, then generate a ready-to-run Lua script.
        </p>
      </header>

      <section className="grid">
        <article className="card form-card">
          <h2>Player Profile</h2>

          <div className="row two-col">
            <label>
              First name
              <input value={form.firstName} onChange={(e) => updateField('firstName', e.target.value)} />
            </label>
            <label>
              Last name
              <input value={form.lastName} onChange={(e) => updateField('lastName', e.target.value)} />
            </label>
          </div>

          <div className="row two-col">
            <label>
              Jersey name
              <input value={form.jerseyName} onChange={(e) => updateField('jerseyName', e.target.value.toUpperCase())} />
            </label>
            <label>
              Age
              <input
                type="number"
                min="15"
                max="40"
                value={form.age}
                onChange={(e) => updateField('age', Number(e.target.value))}
              />
            </label>
          </div>

          <div className="row three-col">
            <label>
              Position
              <select value={form.position} onChange={(e) => updateField('position', e.target.value)}>
                {Object.keys(POSITION_WEIGHTS).map((positionKey) => (
                  <option key={positionKey} value={positionKey}>
                    {positionKey}
                  </option>
                ))}
              </select>
            </label>
            <label>
              Start template
              <select value={form.template} onChange={(e) => updateField('template', e.target.value)}>
                {Object.entries(STARTING_TEMPLATES).map(([key, cfg]) => (
                  <option key={key} value={key}>
                    {cfg.label}
                  </option>
                ))}
              </select>
            </label>
            <label>
              Target division
              <select value={form.targetDivision} onChange={(e) => updateField('targetDivision', e.target.value)}>
                {DIVISION_OPTIONS.map((division) => (
                  <option key={division} value={division}>
                    {division}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <h3>Rating Questions</h3>
          <p className="hint">Rate each area honestly from 35 to 99. Overall is suggested automatically for your position and start template.</p>

          <div className="slider-group">
            {Object.entries(form.ratings).map(([key, value]) => (
              <label key={key}>
                <span>{key}</span>
                <input
                  type="range"
                  min="35"
                  max="99"
                  value={value}
                  onChange={(e) => updateRating(key, e.target.value)}
                />
                <strong>{value}</strong>
              </label>
            ))}
          </div>

          <div className="row two-col">
            <label>
              Potential
              <input
                type="number"
                min="40"
                max="99"
                value={form.potential}
                onChange={(e) => updateField('potential', clamp(Number(e.target.value), 40, 99))}
              />
            </label>
            <label>
              Player ID
              <input
                type="number"
                min="50000"
                max="99999"
                value={form.playerId}
                onChange={(e) => updateField('playerId', clamp(Number(e.target.value), 50000, 99999))}
              />
            </label>
          </div>

          <div className="row three-col">
            <label>
              Height (cm)
              <input
                type="number"
                min="150"
                max="210"
                value={form.height}
                onChange={(e) => updateField('height', clamp(Number(e.target.value), 150, 210))}
              />
            </label>
            <label>
              Weight (kg)
              <input
                type="number"
                min="50"
                max="120"
                value={form.weight}
                onChange={(e) => updateField('weight', clamp(Number(e.target.value), 50, 120))}
              />
            </label>
            <label>
              Nationality ID
              <input
                type="number"
                min="1"
                max="300"
                value={form.nationality}
                onChange={(e) => updateField('nationality', clamp(Number(e.target.value), 1, 300))}
              />
            </label>
          </div>

          <label className="checkbox-row">
            <input
              type="checkbox"
              checked={form.addToUserTeam}
              onChange={(e) => updateField('addToUserTeam', e.target.checked)}
            />
            Transfer directly to my user team after create
          </label>
        </article>

        <aside className="card summary-card">
          <h2>Build Summary</h2>
          <p>
            <strong>
              {form.firstName} {form.lastName}
            </strong>{' '}
            - {form.position} - age {form.age}
          </p>
          <div className="pill-row">
            <div className="pill">
              <span>Suggested OVR</span>
              <strong>{suggestedOverall}</strong>
            </div>
            <div className="pill">
              <span>Potential</span>
              <strong>{form.potential}</strong>
            </div>
            <div className="pill">
              <span>Category Avg</span>
              <strong>{averageCategory}</strong>
            </div>
          </div>

          <p className="hint">
            Current template range: {STARTING_TEMPLATES[form.template].min}-{STARTING_TEMPLATES[form.template].max}. This keeps
            career growth fun instead of starting fully maxed.
          </p>

          <div className="lua-header">
            <h3>Generated Lua</h3>
            <button type="button" onClick={copyLuaScript}>
              Copy
            </button>
          </div>
          <textarea readOnly value={luaScript} rows={22} />
        </aside>
      </section>

      <footer className="next-step">
        <p>Next step in the next commit: multi-player squad builder and batch Lua export for full custom clubs.</p>
      </footer>
    </main>
  )
}

export default App
